version: '3.1'

services:

  application:
    image: mikhailtarasevich/social-media-api
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/social_media_db
    ports:
      - 8888:8888
    networks:
      - network

  postgres:
    image: mikhailtarasevich/db-social-media-api
    volumes:
          - postgres:/var/lib/postgresql/data
          - ./src/main/resources/sql/schema.sql:/docker-entrypoint-initdb.d/create_tables.sql
          - ./src/main/resources/sql/data.sql:/docker-entrypoint-initdb.d/fill_tables.sql
    environment:
          POSTGRES_PASSWORD: 1111
          POSTGRES_USER: postgres
          POSTGRES_DB: social_media_db
          PGDATA: /var/lib/postgresql/data
    ports:
      - 5050:5432
    restart: always
    networks:
      - network

volumes:
  postgres:

networks:
  network:
    driver: bridge